version: "3.3"
services:
  backend:
    build:      
      dockerfile: ./backend/Dockerfile
    container_name: backend    
    ports:
      - 81:81        

  frontend:
    build:      
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    ports:
      - 80:80    
    depends_on:
      - backend